### PR TITLE
added word download and deleted landing page 

### PR DESCRIPTION
**Pull request by RAJU2529**
its my own PR , just added download word and deleted  landing page words

### CODE REVIEW

**Comment by RAJU2529** [comment]
@dan-wesley . Sorry sir I can't understand what you said

**Comment by dan-wesley** [comment]
@RAJU2529 
You want to change the file named "microsoft-edge-update-policies.md", correct?
I'm saying that this file can't be edited directly and updated the way you're doing it.

**Comment by RAJU2529** [comment]
@dan-wesley . Not that sir.  I have edited the content inside the article.
I am waiting for approval of PR and reviewing of grammatical mistakes From reviewer.

**Comment by dan-wesley** [comment]
@RAJU2529 
that change will not get approved. This article is generated from a policy source code file. To make changes you have to get a change request opened and sent to the developers who can make the change.

**Comment by RAJU2529** [comment]
@dan-wesley . I don't know who is the author of the article. If you from Microsoft means, then you can find easily, send the alert to author or developer

**Comment by dan-wesley** [comment]
@RAJU2529 
As it happens, I am one of the authors of the MS content. To make the change you want I'd have to open a developer change request. I won't because the change you've made doesn't fit our standard document template for the See also link in question.

**Comment by RAJU2529** [comment]
@dan-wesley . Then what should I do sir?

**Comment by dan-wesley** [comment]
@RAJU2529 
Since the change you want is totally out of sync with all the other Microsoft Edge Enterprise landing page links in the documentation, close your PR.

**Pull request closed without merging**
